# Form implementation generated from reading ui file 'sobre.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Sobre(object):
    def setupUi(self, Sobre):
        Sobre.setObjectName("Sobre")
        Sobre.resize(401, 213)
        self.widget = QtWidgets.QWidget(parent=Sobre)
        self.widget.setGeometry(QtCore.QRect(20, 30, 367, 153))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setStyleSheet("\n"
"font: 87 16pt \"Arial Black\";\n"
"")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setStyleSheet("font: 10pt \"Segoe UI Emoji\";")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setStyleSheet("font: 10pt \"Segoe UI Emoji\";")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        self.label_4.setStyleSheet("font: 10pt \"Segoe UI Emoji\";")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(parent=self.widget)
        self.label_5.setStyleSheet("font: 10pt \"Segoe UI Emoji\";")
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.label_6 = QtWidgets.QLabel(parent=self.widget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)

        self.retranslateUi(Sobre)
        QtCore.QMetaObject.connectSlotsByName(Sobre)

    def retranslateUi(self, Sobre):
        _translate = QtCore.QCoreApplication.translate
        Sobre.setWindowTitle(_translate("Sobre", "Form"))
        self.label.setText(_translate("Sobre", "<html><head/><body><p align=\"center\">Bryan Sistemas ©️</p></body></html>"))
        self.label_2.setText(_translate("Sobre", "Projeto gerenciamento de estoque, desenvolvido com intuíto "))
        self.label_3.setText(_translate("Sobre", "de aprofundar os conhecimentos obtidos na area."))
        self.label_4.setText(_translate("Sobre", "ANÁLISE E DESENVOLVIMENTO DE SISTEMAS / ANHANGUERA "))
        self.label_5.setText(_translate("Sobre", "<html><head/><body><p align=\"center\">GOVERNADOR VALADARES 2024</p></body></html>"))
        self.label_6.setText(_translate("Sobre", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Todos os direitos reservados ©️ 2024</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Sobre = QtWidgets.QWidget()
    ui = Ui_Sobre()
    ui.setupUi(Sobre)
    Sobre.show()
    sys.exit(app.exec())
