# Form implementation generated from reading ui file 'aviso.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Sobre(object):
    def setupUi(self, Sobre):
        Sobre.setObjectName("Sobre")
        Sobre.resize(421, 160)
        self.widget = QtWidgets.QWidget(parent=Sobre)
        self.widget.setGeometry(QtCore.QRect(10, 20, 411, 111))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)

        self.retranslateUi(Sobre)
        QtCore.QMetaObject.connectSlotsByName(Sobre)

    def retranslateUi(self, Sobre):
        _translate = QtCore.QCoreApplication.translate
        Sobre.setWindowTitle(_translate("Sobre", "Form"))
        self.label.setText(_translate("Sobre", "<html><head/><body><p><span style=\" font-size:14pt;\">Quantidade</span><span style=\" font-size:14pt; color:#ff0000;\"> superior </span><span style=\" font-size:14pt;\">a que temos em estoque !</span></p></body></html>"))
        self.label_2.setText(_translate("Sobre", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ff0000;\">VERIFIQUE !</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Sobre = QtWidgets.QWidget()
    ui = Ui_Sobre()
    ui.setupUi(Sobre)
    Sobre.show()
    sys.exit(app.exec())
